// Generated by Selenium IDE
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using Xunit;
using OpenQA.Selenium.Edge;

public class SuiteTests : IDisposable
{
    public IWebDriver driver { get; private set; }
    public IDictionary<String, Object> vars { get; private set; }
    public IJavaScriptExecutor js { get; private set; }
    public SuiteTests()
    {
        var edgeOptions = new EdgeOptions();
        edgeOptions.AddArguments("--headless");
        edgeOptions.AddArguments("--window-size=1920,1080");
        edgeOptions.AddArguments("--start-maximized");
        driver = new EdgeDriver(edgeOptions);
        js = (IJavaScriptExecutor)driver;
        vars = new Dictionary<String, Object>();
    }
    public void Dispose()
    {
        driver.Quit();
    }

    [Fact]
    public void Humongousagain() {
        driver.Navigate().GoToUrl("https://testing-accelerator-appsvc-jdg20230308.azurewebsites.net/");
        driver.Manage().Window.Size = new System.Drawing.Size(1920, 1080);
        driver.FindElement(By.LinkText("Health Checks")).Click();
        {
        WebDriverWait wait = new WebDriverWait(driver, System.TimeSpan.FromSeconds(10));
        wait.Until(driver => driver.FindElements(By.CssSelector("tr:nth-child(1) > td:nth-child(4)")).Count > 0);
        }
        Assert.Equal(driver.FindElement(By.CssSelector("tr:nth-child(1) > td:nth-child(4)")).Text, "I feel healthy");
        driver.Navigate().GoToUrl("https://testing-accelerator-appsvc-jdg20230308.azurewebsites.net/submit-health-check");
        driver.FindElement(By.Name("patientid")).Click();
        driver.FindElement(By.Name("patientid")).SendKeys("22");
        driver.FindElement(By.Name("healthstatus")).Click();
        driver.FindElement(By.Name("healthstatus")).SendKeys("good");
        Assert.Equal(driver.FindElement(By.CssSelector("button:nth-child(6)")).Text, "Submit");
        driver.FindElement(By.XPath("//button[@type=\'submit\']")).Click();
        driver.Navigate().GoToUrl("https://testing-accelerator-appsvc-jdg20230308.azurewebsites.net/health-checks");
        {
        WebDriverWait wait = new WebDriverWait(driver, System.TimeSpan.FromSeconds(10));
        wait.Until(driver => driver.FindElements(By.CssSelector("tr:nth-child(4) > td:nth-child(4)")).Count > 0);
        }
        Assert.Equal(driver.FindElement(By.CssSelector("tr:nth-child(4) > td:nth-child(4)")).Text, "good");
    }
}
